### ISSUE TITLE
BlueMap and MapTowny Error

### ISSUE THREAD

**Issue by Darklom** [TownyAdvanced/MapTowny#33]
## Describe the Bug

Receive the following error on console with the use of BlueMap and MapTowny

"[22:18:18 ERROR]: [BlueMap] BlueMapAPI: A BlueMapAPI listener threw an exception (onEnable)!
java.lang.NoSuchMethodError: 'java.util.Optional de.bluecolored.bluemap.api.BlueMapAPI.getWorld(java.util.UUID)'
        at me.silverwolfg11.maptowny.platform.bluemap.BlueMapPlatform.isWorldEnabled(BlueMapPlatform.java:94) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.managers.TownyLayerManager.initialize(TownyLayerManager.java:120) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.platform.bluemap.BlueMapPlatform.lambda$onFirstInitialize$2(BlueMapPlatform.java:67) ~[maptowny-2.0.1.jar:?]
        at de.bluecolored.bluemap.api.BlueMapAPI.registerInstance(BlueMapAPI.java:201) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.api.BlueMapAPIImpl.register(BlueMapAPIImpl.java:137) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:319) ~[BlueMap-3.3-spigot.jar:?]
        at de.bluecolored.bluemap.bukkit.BukkitPlugin.lambda$onEnable$0(BukkitPlugin.java:147) ~[BlueMap-3.3-spigot.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-135]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]"
        
## Expected Behavior
No error

### Plugin Version
maptowny-2.0.1

### Towny Version
v0.98.3.6

### Pl3xMap Version
Bluemap version v3.3

### Server Software Version
Paper version git-Paper-135 (MC: 1.19.2)

**Comment by silverwolfg11** [comment]
Thanks for reporting this issue. It looks like the latest versions of BlueMap have changed their API a bit and also what Java version they support. 

This will be fixed in the next release of MapTowny. In the meantime, older versions should work.

**Comment by silverwolfg11** [comment]
Fixed in [version 2.1.0](https://github.com/TownyAdvanced/MapTowny/releases/tag/v2.1.0).
