### ISSUE TITLE
[18:05:23 ERROR]: Error occurred while enabling MapTowny v2.0.1 (Is it up to date?)

### ISSUE THREAD

**Issue by SnowzNZ** [TownyAdvanced/MapTowny#34]
## Describe the Bug
Error in console and in-game when running /maptowny.
`[18:05:23 ERROR]: Error occurred while enabling MapTowny v2.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net.pl3x.map.api.Pl3xMapProvider
        at me.silverwolfg11.maptowny.platform.pl3xmap.Pl3xMapPlatform.isWorldEnabled(Pl3xMapPlatform.java:42) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.managers.TownyLayerManager.initialize(TownyLayerManager.java:120) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.managers.TownyLayerManager$$Lambda$9753/0x00000000854d7b38.run(Unknown Source) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.platform.MapPlatform.onFirstInitialize(MapPlatform.java:56) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.managers.TownyLayerManager.<init>(TownyLayerManager.java:94) ~[maptowny-2.0.1.jar:?]
        at me.silverwolfg11.maptowny.MapTowny.onEnable(MapTowny.java:80) ~[maptowny-2.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer$$Lambda$4307/0x00000000ba8ea590.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.pl3x.map.api.Pl3xMapProvider
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1112) ~[?:?]
        ... 18 more`
        
 `[18:09:56 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'maptowny' in plugin MapTowny v2.0.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.server.network.PlayerConnection$$Lambda$11148/0x00000000c0662aa8.run(Unknown Source) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at net.minecraft.util.thread.IAsyncTaskHandler$$Lambda$11149/0x00000000c0662da0.get(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1819]
        at net.minecraft.server.MinecraftServer$$Lambda$4307/0x00000000ba8ea590.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Thread.java:884) ~[?:?]`

## Expected Behavior
Unsure as this is the first time I have tried using this plugin.

### Plugin Version
v2.0.1

### Towny Version
0.98.3.12

### Pl3xMap Version
1.19.2-314

### Server Software Version
Purpur-1819 1.19.2

**Comment by silverwolfg11** [comment]
Hi, sorry for the delayed response. This error occurs because the MapTowny plugin does not currently support the latest version of Pl3xMap.

This may sound unusual, but until recently Pl3xMap was archived, then it was revived but under-going development.

Thank you for alerting me to this issue. I'm currently a little busy with other things at the moment, but I hope to have a minor release that has support for this within 2-4 weeks.

**Comment by silverwolfg11** [comment]
Fixed in [version 2.1.0](https://github.com/TownyAdvanced/MapTowny/releases/tag/v2.1.0).
